/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

/**
 *
 * @author Andrew
 */
public class WeissSchwarzGameBoard extends javax.swing.JFrame {
    /**
     * Creates new form WarGui
     */
    public WeissSchwarzGameBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Player1HandCard5 = new javax.swing.JLabel();
        Player2ClockLabel5 = new javax.swing.JLabel();
        Player2SupportCard1 = new javax.swing.JLabel();
        Player2SupportCard2 = new javax.swing.JLabel();
        Player1SupportCard1 = new javax.swing.JLabel();
        Player1SupportCard2 = new javax.swing.JLabel();
        Player1LevelCard1 = new javax.swing.JLabel();
        Player2LevelCard3 = new javax.swing.JLabel();
        AIDiscardPileAmt = new javax.swing.JLabel();
        PlayerDiscardPileAmt = new javax.swing.JLabel();
        AIDeckAmt = new javax.swing.JLabel();
        Player2ClockLabel4 = new javax.swing.JLabel();
        Player2ClockLabel3 = new javax.swing.JLabel();
        Player2StockCard5 = new javax.swing.JLabel();
        Player2ClockLabel2 = new javax.swing.JLabel();
        Player2AttackCard2 = new javax.swing.JLabel();
        Player2AttackCard3 = new javax.swing.JLabel();
        Player2AttackCard1 = new javax.swing.JLabel();
        Player1HandCard4 = new javax.swing.JLabel();
        Player1HandCard3 = new javax.swing.JLabel();
        Player1HandCard2 = new javax.swing.JLabel();
        Player1StockCard1 = new javax.swing.JLabel();
        Player1StockCard2 = new javax.swing.JLabel();
        Player1AttackCard1 = new javax.swing.JLabel();
        Player1AttackCard3 = new javax.swing.JLabel();
        Player1AttackCard2 = new javax.swing.JLabel();
        Player1HandCard1 = new javax.swing.JLabel();
        Player1StockCard3 = new javax.swing.JLabel();
        Player1StockCard4 = new javax.swing.JLabel();
        Player1StockCard5 = new javax.swing.JLabel();
        Player2ClockLabel1 = new javax.swing.JLabel();
        Player2StockCard4 = new javax.swing.JLabel();
        Player2StockCard3 = new javax.swing.JLabel();
        Player2StockCard2 = new javax.swing.JLabel();
        Player2StockCard1 = new javax.swing.JLabel();
        Player1DeckLabel = new javax.swing.JLabel();
        Player2DeckLabel = new javax.swing.JLabel();
        AIDiscardPile2 = new javax.swing.JLabel();
        Player1WaitingRoomLabel = new javax.swing.JLabel();
        PlayerDiscardPile3 = new javax.swing.JLabel();
        Player1ClockLabel1 = new javax.swing.JLabel();
        Player1ClockLabel2 = new javax.swing.JLabel();
        Player1ClockLabel3 = new javax.swing.JLabel();
        Player1ClockLabel4 = new javax.swing.JLabel();
        Player1ClockLabel5 = new javax.swing.JLabel();
        Player1ClimaxCardLabel = new javax.swing.JLabel();
        Player1LevelCard2 = new javax.swing.JLabel();
        Player1LevelCard3 = new javax.swing.JLabel();
        AIDiscardPile3 = new javax.swing.JLabel();
        Player2LevelCard2 = new javax.swing.JLabel();
        Player2ClimaxCardLabel = new javax.swing.JLabel();
        AIDiscardPileAmt1 = new javax.swing.JLabel();
        AIDiscardPileAmt2 = new javax.swing.JLabel();
        Player2HandCard3 = new javax.swing.JLabel();
        Player2HandCard2 = new javax.swing.JLabel();
        Player2HandCard4 = new javax.swing.JLabel();
        Player2HandCard1 = new javax.swing.JLabel();
        Player2HandCard5 = new javax.swing.JLabel();
        Player2LevelCard1 = new javax.swing.JLabel();
        AIDeckAmt1 = new javax.swing.JLabel();
        AIDeckAmt2 = new javax.swing.JLabel();
        AIDeckAmt3 = new javax.swing.JLabel();
        AIDeckAmt4 = new javax.swing.JLabel();
        AIDeckAmt5 = new javax.swing.JLabel();
        AIDeckAmt6 = new javax.swing.JLabel();
        AIDeckAmt7 = new javax.swing.JLabel();
        AIDeckAmt8 = new javax.swing.JLabel();
        AIDeckAmt9 = new javax.swing.JLabel();
        AIDeckAmt10 = new javax.swing.JLabel();
        AIDeckAmt11 = new javax.swing.JLabel();
        AIDeckAmt12 = new javax.swing.JLabel();
        AIDeckAmt13 = new javax.swing.JLabel();
        AIDiscardPileAmt3 = new javax.swing.JLabel();
        AIDiscardPileAmt4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        startMenu = new javax.swing.JMenu();
        endScreen = new javax.swing.JMenu();
        restart = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Player1HandCard5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player1HandCard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1HandCard5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 820, 70, -1));

        Player2ClockLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2ClockLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        Player2SupportCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2SupportCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        Player2SupportCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2SupportCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));

        Player1SupportCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1SupportCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 580, -1, -1));

        Player1SupportCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1SupportCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, -1, -1));

        Player1LevelCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fh.png"))); // NOI18N
        getContentPane().add(Player1LevelCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 720, -1, -1));

        Player2LevelCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fh.png"))); // NOI18N
        getContentPane().add(Player2LevelCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, -1));

        AIDiscardPileAmt.setText("Memory");
        getContentPane().add(AIDiscardPileAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 50, -1));

        PlayerDiscardPileAmt.setText("Deck");
        getContentPane().add(PlayerDiscardPileAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 820, 40, -1));

        AIDeckAmt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AIDeckAmt.setText("Stock");
        getContentPane().add(AIDeckAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 430, 50, -1));

        Player2ClockLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2ClockLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, -1));

        Player2ClockLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2ClockLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        Player2StockCard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2StockCard5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 330, -1, -1));

        Player2ClockLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2ClockLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        Player2AttackCard2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player2AttackCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2AttackCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, -1, -1));

        Player2AttackCard3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player2AttackCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2AttackCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        Player2AttackCard1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player2AttackCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2AttackCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        Player1HandCard4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player1HandCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1HandCard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 820, 70, -1));

        Player1HandCard3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player1HandCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1HandCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 820, 70, -1));

        Player1HandCard2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player1HandCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1HandCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 820, 70, -1));

        Player1StockCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1StockCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 690, 70, -1));

        Player1StockCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1StockCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 640, 70, -1));

        Player1AttackCard1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player1AttackCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1AttackCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 460, 70, -1));

        Player1AttackCard3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player1AttackCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1AttackCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 70, -1));

        Player1AttackCard2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player1AttackCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1AttackCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 460, 70, -1));

        Player1HandCard1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player1HandCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1HandCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 820, 70, -1));

        Player1StockCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1StockCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 70, -1));

        Player1StockCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1StockCard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, -1, -1));

        Player1StockCard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1StockCard5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 70, -1));

        Player2ClockLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2ClockLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        Player2StockCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2StockCard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 290, -1, -1));

        Player2StockCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2StockCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, -1, -1));

        Player2StockCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2StockCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, -1, -1));

        Player2StockCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2StockCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 180, -1, -1));

        Player1DeckLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        Player1DeckLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Player1DeckLabelMouseClicked(evt);
            }
        });
        getContentPane().add(Player1DeckLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 720, -1, -1));

        Player2DeckLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2DeckLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        AIDiscardPile2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(AIDiscardPile2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        Player1WaitingRoomLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1WaitingRoomLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 600, -1, -1));

        PlayerDiscardPile3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fh.png"))); // NOI18N
        getContentPane().add(PlayerDiscardPile3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 510, -1, -1));

        Player1ClockLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1ClockLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 700, -1, -1));

        Player1ClockLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1ClockLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 700, 70, -1));

        Player1ClockLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1ClockLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 700, 70, -1));

        Player1ClockLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1ClockLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 700, 70, -1));

        Player1ClockLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fv.png"))); // NOI18N
        getContentPane().add(Player1ClockLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 700, 70, -1));

        Player1ClimaxCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fh.png"))); // NOI18N
        getContentPane().add(Player1ClimaxCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 590, -1, -1));

        Player1LevelCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fh.png"))); // NOI18N
        getContentPane().add(Player1LevelCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 700, -1, -1));

        Player1LevelCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b1fh.png"))); // NOI18N
        getContentPane().add(Player1LevelCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 680, -1, -1));

        AIDiscardPile3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fh.png"))); // NOI18N
        getContentPane().add(AIDiscardPile3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        Player2LevelCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fh.png"))); // NOI18N
        getContentPane().add(Player2LevelCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        Player2ClimaxCardLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fh.png"))); // NOI18N
        getContentPane().add(Player2ClimaxCardLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        AIDiscardPileAmt1.setText("Deck");
        getContentPane().add(AIDiscardPileAmt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 40, -1));

        AIDiscardPileAmt2.setText("Waiting Room");
        getContentPane().add(AIDiscardPileAmt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 90, -1));

        Player2HandCard3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player2HandCard3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2HandCard3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 70, -1));

        Player2HandCard2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player2HandCard2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2HandCard2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 70, -1));

        Player2HandCard4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player2HandCard4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2HandCard4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 70, -1));

        Player2HandCard1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player2HandCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2HandCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 70, -1));

        Player2HandCard5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player2HandCard5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fv.png"))); // NOI18N
        getContentPane().add(Player2HandCard5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 70, -1));

        Player2LevelCard1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/b2fh.png"))); // NOI18N
        getContentPane().add(Player2LevelCard1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        AIDeckAmt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AIDeckAmt1.setText("Hand");
        getContentPane().add(AIDeckAmt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 920, 50, -1));

        AIDeckAmt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AIDeckAmt2.setText("Hand");
        getContentPane().add(AIDeckAmt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 50, -1));

        AIDeckAmt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AIDeckAmt3.setText("Clock");
        getContentPane().add(AIDeckAmt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 50, -1));

        AIDeckAmt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AIDeckAmt4.setText("Climax");
        getContentPane().add(AIDeckAmt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 50, -1));

        AIDeckAmt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AIDeckAmt5.setText("Stock");
        getContentPane().add(AIDeckAmt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 800, 50, -1));

        AIDeckAmt6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AIDeckAmt6.setText("Clock");
        getContentPane().add(AIDeckAmt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 800, 50, -1));

        AIDeckAmt7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AIDeckAmt7.setText("Level");
        getContentPane().add(AIDeckAmt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 50, -1));

        AIDeckAmt8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AIDeckAmt8.setText("Attack Area");
        getContentPane().add(AIDeckAmt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 100, -1));

        AIDeckAmt9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AIDeckAmt9.setText("Climax");
        getContentPane().add(AIDeckAmt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 660, 50, -1));

        AIDeckAmt10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AIDeckAmt10.setText("Level");
        getContentPane().add(AIDeckAmt10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 800, 50, -1));

        AIDeckAmt11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AIDeckAmt11.setText("Support Area");
        getContentPane().add(AIDeckAmt11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 100, -1));

        AIDeckAmt12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AIDeckAmt12.setText("Support Area");
        getContentPane().add(AIDeckAmt12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 680, 100, -1));

        AIDeckAmt13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AIDeckAmt13.setText("Attack Area");
        getContentPane().add(AIDeckAmt13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, 100, -1));

        AIDiscardPileAmt3.setText("Waiting Room");
        getContentPane().add(AIDiscardPileAmt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 700, 90, -1));

        AIDiscardPileAmt4.setText("Memory");
        getContentPane().add(AIDiscardPileAmt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 580, 50, -1));

        startMenu.setBorder(new javax.swing.border.MatteBorder(null));
        startMenu.setText("Go to Start Menu");
        jMenuBar1.add(startMenu);

        endScreen.setBorder(new javax.swing.border.MatteBorder(null));
        endScreen.setText("Go to End Game Screen");
        endScreen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endScreenMouseClicked(evt);
            }
        });
        jMenuBar1.add(endScreen);

        restart.setBorder(new javax.swing.border.MatteBorder(null));
        restart.setText("Restart");
        jMenuBar1.add(restart);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Player1DeckLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Player1DeckLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Player1DeckLabelMouseClicked

    private void endScreenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endScreenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_endScreenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeissSchwarzGameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeissSchwarzGameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeissSchwarzGameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeissSchwarzGameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeissSchwarzGameBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel AIDeckAmt;
    protected javax.swing.JLabel AIDeckAmt1;
    protected javax.swing.JLabel AIDeckAmt10;
    protected javax.swing.JLabel AIDeckAmt11;
    protected javax.swing.JLabel AIDeckAmt12;
    protected javax.swing.JLabel AIDeckAmt13;
    protected javax.swing.JLabel AIDeckAmt2;
    protected javax.swing.JLabel AIDeckAmt3;
    protected javax.swing.JLabel AIDeckAmt4;
    protected javax.swing.JLabel AIDeckAmt5;
    protected javax.swing.JLabel AIDeckAmt6;
    protected javax.swing.JLabel AIDeckAmt7;
    protected javax.swing.JLabel AIDeckAmt8;
    protected javax.swing.JLabel AIDeckAmt9;
    protected javax.swing.JLabel AIDiscardPile2;
    protected javax.swing.JLabel AIDiscardPile3;
    protected javax.swing.JLabel AIDiscardPileAmt;
    protected javax.swing.JLabel AIDiscardPileAmt1;
    protected javax.swing.JLabel AIDiscardPileAmt2;
    protected javax.swing.JLabel AIDiscardPileAmt3;
    protected javax.swing.JLabel AIDiscardPileAmt4;
    protected javax.swing.JLabel Player1AttackCard1;
    protected javax.swing.JLabel Player1AttackCard2;
    protected javax.swing.JLabel Player1AttackCard3;
    protected javax.swing.JLabel Player1ClimaxCardLabel;
    protected javax.swing.JLabel Player1ClockLabel1;
    protected javax.swing.JLabel Player1ClockLabel2;
    protected javax.swing.JLabel Player1ClockLabel3;
    protected javax.swing.JLabel Player1ClockLabel4;
    protected javax.swing.JLabel Player1ClockLabel5;
    protected javax.swing.JLabel Player1DeckLabel;
    protected javax.swing.JLabel Player1HandCard1;
    protected javax.swing.JLabel Player1HandCard2;
    protected javax.swing.JLabel Player1HandCard3;
    protected javax.swing.JLabel Player1HandCard4;
    protected javax.swing.JLabel Player1HandCard5;
    protected javax.swing.JLabel Player1LevelCard1;
    protected javax.swing.JLabel Player1LevelCard2;
    protected javax.swing.JLabel Player1LevelCard3;
    protected javax.swing.JLabel Player1StockCard1;
    protected javax.swing.JLabel Player1StockCard2;
    protected javax.swing.JLabel Player1StockCard3;
    protected javax.swing.JLabel Player1StockCard4;
    protected javax.swing.JLabel Player1StockCard5;
    protected javax.swing.JLabel Player1SupportCard1;
    protected javax.swing.JLabel Player1SupportCard2;
    protected javax.swing.JLabel Player1WaitingRoomLabel;
    protected javax.swing.JLabel Player2AttackCard1;
    protected javax.swing.JLabel Player2AttackCard2;
    protected javax.swing.JLabel Player2AttackCard3;
    protected javax.swing.JLabel Player2ClimaxCardLabel;
    protected javax.swing.JLabel Player2ClockLabel1;
    protected javax.swing.JLabel Player2ClockLabel2;
    protected javax.swing.JLabel Player2ClockLabel3;
    protected javax.swing.JLabel Player2ClockLabel4;
    protected javax.swing.JLabel Player2ClockLabel5;
    protected javax.swing.JLabel Player2DeckLabel;
    protected javax.swing.JLabel Player2HandCard1;
    protected javax.swing.JLabel Player2HandCard2;
    protected javax.swing.JLabel Player2HandCard3;
    protected javax.swing.JLabel Player2HandCard4;
    protected javax.swing.JLabel Player2HandCard5;
    protected javax.swing.JLabel Player2LevelCard1;
    protected javax.swing.JLabel Player2LevelCard2;
    protected javax.swing.JLabel Player2LevelCard3;
    protected javax.swing.JLabel Player2StockCard1;
    protected javax.swing.JLabel Player2StockCard2;
    protected javax.swing.JLabel Player2StockCard3;
    protected javax.swing.JLabel Player2StockCard4;
    protected javax.swing.JLabel Player2StockCard5;
    protected javax.swing.JLabel Player2SupportCard1;
    protected javax.swing.JLabel Player2SupportCard2;
    protected javax.swing.JLabel PlayerDiscardPile3;
    protected javax.swing.JLabel PlayerDiscardPileAmt;
    protected javax.swing.JMenu endScreen;
    private javax.swing.JMenuBar jMenuBar1;
    protected javax.swing.JMenu restart;
    protected javax.swing.JMenu startMenu;
    // End of variables declaration//GEN-END:variables
}
